We download sources instead of having them in the depot

diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -4,14 +4,14 @@
 # will be located in the current directory, regarding the last argument.
 
 # Exit on command errors and treat unset variables as an error
-set -eu
+#set -eu
 
-TRAP_ON () {    # Activate signal capture
-        trap EXIT_PROPERLY ERR  # Capturing ex it signals on error
-}
+#TRAP_ON () {    # Activate signal capture
+#        trap EXIT_PROPERLY ERR  # Capturing ex it signals on error
+#}
 
 # Active trap pour arrêter le script si une erreur est détectée.
-TRAP_ON
+#TRAP_ON
 
 # See comments in install script
 app=$YNH_APP_INSTANCE_NAME
@@ -48,16 +48,6 @@ then
 else
         echo "Nothing to do"
 fi
-
-### MySQL (remove if not used) ###
-# If a MySQL database is used:
-# # Create and restore the database
-# dbname=$app
-# dbuser=$app
-# dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
-# ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
-# ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" < ./dump.sql
-### MySQL end ###
 
 # Restore NGINX configuration
 sudo cp -a ./nginx.conf $finalnginxconf
