Fix

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,127 +1,239 @@
 #!/bin/bash
-set -eu
 
-# We retrieve app parameters
-app=$YNH_APP_INSTANCE_NAME
+#=================================================
+# GENERIC START
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-# Source app helpers
-source .fonctions
+source _common.sh
 source /usr/share/yunohost/helpers
 
-# We check variables are not empty
-CHECK_VAR "$app" "app name not set"
+#=================================================
+# LOAD SETTINGS
+#=================================================
+ynh_script_progression --message="Loading installation settings..." --time --weight=1
 
-path=$(ynh_app_setting_get $app path)
-domain=$(ynh_app_setting_get $app domain)
-final_path=$(ynh_app_setting_get $app final_path)
-finalnginxconf=$(ynh_app_setting_get $app finalnginxconf)
-finalphpconf=$(ynh_app_setting_get $app finalphpconf)
-calibre=$(ynh_app_setting_get $app calibre)
-basicauthcreate=$(ynh_app_setting_get $app basicauthcreate)
+app=$YNH_APP_INSTANCE_NAME
 
-# We check that calibre path is correct
-CHECK_CALIBRE
+domain=$(ynh_app_setting_get --app=$app --key=domain)
+path_url=$(ynh_app_setting_get --app=$app --key=path)
+admin=$(ynh_app_setting_get --app=$app --key=admin)
+final_path=$(ynh_app_setting_get --app=$app --key=final_path)
+language=$(ynh_app_setting_get --app=$app --key=language)
+db_name=$(ynh_app_setting_get --app=$app --key=db_name)
 
-# Install dependencies using Helpers
-ynh_package_install_from_equivs ../conf/cops-deps.control \
-|| ynh_die "Unable to install dependencies"
+#=================================================
+# CHECK VERSION
+#=================================================
 
-# Removal of old folder and restart from fresh
-SECURE_REMOVE '$final_path'
-sudo mkdir -p $final_path
+### This helper will compare the version of the currently installed app and the version of the upstream package.
+### $upgrade_type can have 2 different values
+### - UPGRADE_APP if the upstream app version has changed
+### - UPGRADE_PACKAGE if only the YunoHost package has changed
+### ynh_check_app_version_changed will stop the upgrade if the app is up to date.
+### UPGRADE_APP should be used to upgrade the core app only if there's an upgrade to do.
+upgrade_type=$(ynh_check_app_version_changed)
 
-# We download the sources and check the md5sum
-cops_file=`sudo cat ../sources/source_file`;
-sudo wget -nv -i ../sources/source_url -O $cops_file
-sudo md5sum -c ../sources/source_md5 --status || (echo "Corrupt source" >&2 && false)
-sudo unzip ${cops_file} -d $final_path
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
+ynh_script_progression --message="Backing up the app before upgrading (may take a while)..." --time --weight=1
 
-# Site adjustments
-sed -i "s@CALIBRETOCHANGE@$calibre@g" ../conf/config_local.php
-timezone=`sudo cat /etc/timezone`;
-sed -i "s@TIMEZONETOCHANGE@$timezone@g" ../conf/config_local.php
+# Backup the current version of the app
+ynh_backup_before_upgrade
+ynh_clean_setup () {
+    # Restore it if the upgrade fails
+    ynh_restore_upgradebackup
+}
+# Exit if an error occurs during the execution of the script
+ynh_abort_if_errors
 
-sudo cp ../conf/config_local.php $final_path
-sudo cp ../conf/robots.txt $final_path
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+# STOP SYSTEMD SERVICE
+#=================================================
+ynh_script_progression --message="Stopping a systemd service..." --time --weight=1
 
-# Create cops user and join nextcloud/owncloud/www-data groups
-runninguser="${app}-ynh"
-# 1.  Create the user
-# Create a system account for COPS if it doesn't already exists
-if ! ynh_system_user_exists "$runninguser" ;
-then
-    echo "The user $runninguser does not exist, we can create it"
-    sudo useradd -c "$runninguser system account" \
-       -d $final_path --system --user-group $runninguser \
-       || ynh_die "Unable to create $runninguser system account"
-else
-    echo "The user $runninguser exists, no need to create it"
+ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"
+
+#=================================================
+# ENSURE DOWNWARD COMPATIBILITY
+#=================================================
+ynh_script_progression --message="Ensuring downward compatibility..." --time --weight=1
+
+#
+# N.B. : the followings setting migrations snippets are provided as *EXAMPLES*
+# of what you may want to do in some cases (e.g. a setting was not defined on
+# some legacy installs and you therefore want to initiaze stuff during upgrade)
+#
+
+# If db_name doesn't exist, create it
+#if [ -z "$db_name" ]; then
+#   db_name=$(ynh_sanitize_dbid --db_name=$app)
+#   ynh_app_setting_set --app=$app --key=db_name --value=$db_name
+#fi
+
+# If final_path doesn't exist, create it
+#if [ -z "$final_path" ]; then
+#   final_path=/var/www/$app
+#   ynh_app_setting_set --app=$app --key=final_path --value=$final_path
+#fi
+
+### If nobody installed your app before 4.1,
+### then you may safely remove these lines
+
+# Cleaning legacy permissions
+if ynh_legacy_permissions_exists; then
+    ynh_legacy_permissions_delete_all
+
+    ynh_app_setting_delete --app=$app --key=is_public
 fi
 
-ynh_app_setting_set "$app" runninguser "$runninguser"
-
-# 2. Add cops-ynh to groups www-data and nextcloud/owncloud if they exist
-sudo usermod -a -G www-data $runninguser
-for filesharing in "nextcloud" "owncloud"; do
-    app_id=$(sudo yunohost app list --installed -f "$filesharing" \
-            --output-as json | grep -Po '"id":[ ]?"\K.*?(?=")' | head -1)
-    [[ -z "$app_id" ]] || {
-        sudo usermod -a -G $filesharing $runninguser
-    }
-done
-
-# Set permissions
-sudo chmod ug+rw -R $final_path
-sudo chown -hR $runninguser:$runninguser $final_path
-
-# Add basic auth if requested
-if [ "$basicauthcreate" = "Yes" ];
-then
-	basicauthname=$(ynh_app_setting_get $app basicauthname)
-	basicauthpass=$(ynh_app_setting_get $app basicauthpass)
-
-        # Generation of the htpasswd file according https://www.nginx.com/resources/wiki/community/faq/
-        SALT="$(openssl rand -base64 3)"
-        (SHA1=$(printf "$basicauthpass$SALT" |
-        openssl dgst -binary -sha1 | xxd -ps |
-        sed 's#$#'"`echo -n $SALT | xxd -ps`"'#' |
-        xxd -r -ps |
-        base64);printf "$basicauthname:{SSHA}$SHA1\n" >> ../sources/htpasswd)
-        sudo cp ../sources/htpasswd $final_path
-        sudo chmod 440 $final_path/htpasswd
-        sudo chown www-data:www-data $final_path/htpasswd
-
-        # Modif nginx
-        sed -i "s|^.*\bauth_basic\b.*$|       auth_basic \"Private Library\";|" ../conf/nginx.conf;
-        sed -i "s|^.*\bauth_basic_user_file\b.*$|       auth_basic_user_file $final_path/htpasswd;|" ../conf/nginx.conf;
-else
-        echo "No basic auth";
+if ! ynh_permission_exists --permission="admin"; then
+    # Create the required permissions
+    ynh_permission_create --permission="admin" --url="/admin" --allowed=$admin
 fi
 
-# Modify Nginx configuration file and copy it to Nginx conf.d directory
-sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
-sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
-sed -i "s@NAMETOCHANGE@$app@g" ../conf/nginx.conf
-sudo cp ../conf/nginx.conf $finalnginxconf
-
-# Modify php-fpm configuration file and copy it to php-fpm pool.d directory
-sed -i "s@NAMETOCHANGE@$app@g" ../conf/php-fpm.conf
-sed -i "s@FOLDERTOCHANGE@$final_path@g" ../conf/php-fpm.conf
-sed -i "s@USERTOCHANGE@$runninguser@g" ../conf/php-fpm.conf
-sudo cp ../conf/php-fpm.conf $finalphpconf
-sudo chown root: $finalphpconf
-sudo chmod 644 $finalphpconf
-
-# Make app public if necessary
-is_public=$(ynh_app_setting_get $app is_public)
-if [ "$is_public" = "Yes" ];
-then
-	ynh_app_setting_set $app skipped_uris "/"
-else
-	ynh_app_setting_set $app protected_uris "/"
+# Create a permission if needed
+if ! ynh_permission_exists --permission="api"; then
+    ynh_permission_create --permission="api" --url="/api" --allowed="visitors" --show_tile="false" --protected="true"
 fi
 
-# Reload Nginx and regenerate SSOwat conf
-sudo service php5-fpm reload
-sudo service nginx reload
-sudo yunohost app ssowatconf
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
+ynh_script_progression --message="Making sure dedicated system user exists..." --time --weight=1
+
+# Create a dedicated user (if not existing)
+ynh_system_user_create --username=$app --home_dir="$final_path"
+
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
+if [ "$upgrade_type" == "UPGRADE_APP" ]
+then
+    ynh_script_progression --message="Upgrading source files..." --time --weight=1
+
+    # Download, check integrity, uncompress and patch the source from app.src
+    ynh_setup_source --dest_dir="$final_path"
+fi
+
+# FIXME: this should be managed by the core in the future
+# Here, as a packager, you may have to tweak the ownerhsip/permissions
+# such that the appropriate users (e.g. maybe www-data) can access
+# files in some cases.
+# But FOR THE LOVE OF GOD, do not allow r/x for "others" on the entire folder -
+# this will be treated as a security issue.
+chmod 750 "$final_path"
+chmod -R o-rwx "$final_path"
+chown -R $app:www-data "$final_path"
+
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
+ynh_script_progression --message="Upgrading NGINX web server configuration..." --time --weight=1
+
+# Create a dedicated NGINX config
+ynh_add_nginx_config
+
+#=================================================
+# UPGRADE DEPENDENCIES
+#=================================================
+ynh_script_progression --message="Upgrading dependencies..." --time --weight=1
+
+ynh_install_app_dependencies $pkg_dependencies
+
+#=================================================
+# PHP-FPM CONFIGURATION
+#=================================================
+ynh_script_progression --message="Upgrading PHP-FPM configuration..." --time --weight=1
+
+# Create a dedicated PHP-FPM config
+ynh_add_fpm_config
+
+#=================================================
+# SPECIFIC UPGRADE
+#=================================================
+# ...
+#=================================================
+
+#=================================================
+# UPDATE A CONFIG FILE
+#=================================================
+ynh_script_progression --message="Updating a configuration file..." --time --weight=1
+
+### Same as during install
+###
+### The file will automatically be backed-up if it's found to be manually modified (because
+### ynh_add_config keeps track of the file's checksum)
+
+ynh_add_config --template="some_config_file" --destination="$final_path/some_config_file"
+
+# FIXME: this should be handled by the core in the future
+# You may need to use chmod 600 instead of 400,
+# for example if the app is expected to be able to modify its own config
+chmod 400 "$final_path/some_config_file"
+chown $app:$app "$final_path/some_config_file"
+
+### For more complex cases where you want to replace stuff using regexes,
+### you shoud rely on ynh_replace_string (which is basically a wrapper for sed)
+### When doing so, you also need to manually call ynh_store_file_checksum
+###
+### ynh_replace_string --match_string="match_string" --replace_string="replace_string" --target_file="$final_path/some_config_file"
+### ynh_store_file_checksum --file="$final_path/some_config_file"
+
+#=================================================
+# SETUP SYSTEMD
+#=================================================
+ynh_script_progression --message="Upgrading systemd configuration..." --time --weight=1
+
+# Create a dedicated systemd config
+ynh_add_systemd_config
+
+#=================================================
+# GENERIC FINALIZATION
+#=================================================
+# SETUP LOGROTATE
+#=================================================
+ynh_script_progression --message="Upgrading logrotate configuration..." --time --weight=1
+
+# Use logrotate to manage app-specific logfile(s)
+ynh_use_logrotate --non-append
+
+#=================================================
+# INTEGRATE SERVICE IN YUNOHOST
+#=================================================
+ynh_script_progression --message="Integrating service in YunoHost..." --time --weight=1
+
+yunohost service add $app --description="A short description of the app" --log="/var/log/$app/$app.log"
+
+#=================================================
+# START SYSTEMD SERVICE
+#=================================================
+ynh_script_progression --message="Starting a systemd service..." --time --weight=1
+
+ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"
+
+#=================================================
+# UPGRADE FAIL2BAN
+#=================================================
+ynh_script_progression --message="Reconfiguring Fail2Ban..." --time --weight=1
+
+# Create a dedicated Fail2Ban config
+ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"
+
+#=================================================
+# RELOAD NGINX
+#=================================================
+ynh_script_progression --message="Reloading NGINX web server..." --time --weight=1
+
+ynh_systemd_action --service_name=nginx --action=reload
+
+#=================================================
+# END OF SCRIPT
+#=================================================
+
+ynh_script_progression --message="Upgrade of $app completed" --time --last
